$schema: https://json-schema.org/draft/2020-12/schema
description: An execution instance of a workflow
allOf:
  - $ref: ../ProcessRun/schema.yaml
  - type: object
    properties:
      # Compact form
      describedByWorkflow:
        type: string
        format: uri
        description: Links to the workflow description (wfdesc:Workflow) that was executed
        x-jsonld-id: http://purl.org/wf4ever/wfprov#describedByWorkflow
        x-jsonld-type: '@id'
      # Expanded form
      'http://purl.org/wf4ever/wfprov#describedByWorkflow':
        description: Workflow description in expanded form
        type: array
        items:
          type: object
      hadSubProcessRun:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uri
          required:
            - id
        description: The process runs that were part of this workflow execution
      wasEnactedBy:
        type: string
        format: uri
        description: The workflow engine that executed this workflow
    # Accept either compact or expanded form
    anyOf:
      - required: [describedByWorkflow]
      - required: ['http://purl.org/wf4ever/wfprov#describedByWorkflow']
