$schema: https://json-schema.org/draft/2020-12/schema
description: A note or free-text comment
type: object
properties:
  '@id': { type: string, format: uri, description: Identifier }
  '@type': { type: string, description: RDF type (roterms:Note) }
  name: { type: string, description: Title }
  description: { type: string, description: Narrative description }
required: ['@id']
