{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://purl.org/wf4ever/roterms",
  "title": "Parameter",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Name of the parameter."
    },
    "value": {
      "description": "Value of the parameter."
    },
    "description": {
      "type": "string",
      "description": "Description of the parameter."
    }
  },
  "required": ["name"]
}
