$schema: https://json-schema.org/draft/2020-12/schema
description: Software referenced or used within the research object
type: object
properties:
  '@id': { type: string, format: uri, description: Identifier }
  '@type': { type: string, description: RDF type (roterms:Software) }
  name: { type: string, description: Title }
  description: { type: string, description: Narrative description }
required: ['@id']
