$schema: https://json-schema.org/draft/2020-12/schema
description: An execution instance of a process (based on prov:Activity)
allOf:
  - $ref: https://ogcincubator.github.io/bblock-prov-schema/build/annotated/ogc-utils/prov/schema.yaml#/$defs/Activity
type: object
properties:
  id:
    type: string
    format: uri
    description: Unique identifier for the process run
    x-jsonld-id: '@id'
  type:
    type: string
    description: Type indicator (Activity or sub-type)
    x-jsonld-id: '@type'
  describedByProcess:
    type: string
    format: uri
    description: Links to the process description (wfdesc:Process) that was executed
    x-jsonld-id: http://purl.org/wf4ever/wfprov#describedByProcess
    x-jsonld-type: '@id'
  usedInput:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          format: uri
      required:
        - id
    description: Input artifacts used by this process run
  startedAtTime:
    type: string
    format: date-time
    description: Start time of the execution
  endedAtTime:
    type: string
    format: date-time
    description: End time of the execution
  wasPartOfWorkflowRun:
    type: string
    format: uri
    description: The workflow run that this process run was part of
    x-jsonld-id: http://purl.org/wf4ever/wfprov#wasPartOfWorkflowRun
    x-jsonld-type: '@id'
  wasEnactedBy:
    type: string
    format: uri
    description: The workflow engine that enacted this process run
    x-jsonld-id: http://www.w3.org/ns/prov#wasAssociatedWith
    x-jsonld-type: '@id'
required:
  - id
