$schema: https://json-schema.org/draft/2020-12/schema
description: An execution instance of a process (PROV-O Activity - accepts both compact and expanded JSON-LD)
allOf:
  - $ref: https://ogcincubator.github.io/bblock-prov-schema/build/annotated/ogc-utils/prov/schema.yaml#/$defs/Activity
type: object
properties:
  # Compact form properties
  id:
    type: string
    format: uri
    description: Unique identifier for the process run (compact form)
    x-jsonld-id: '@id'
  type:
    type: string
    description: Type indicator (compact form)
    x-jsonld-id: '@type'
  # Expanded form properties
  '@id':
    type: string
    format: uri
    description: Unique identifier (expanded form)
  '@type':
    description: Type indicator (expanded form - array of URIs)
    oneOf:
      - type: string
      - type: array
  'http://www.w3.org/2000/01/rdf-schema#label':
    description: Label in expanded PROV-O form
    type: array
    items:
      type: object
  'http://www.w3.org/ns/prov#startedAtTime':
    description: Start time in expanded form
    type: array
    items:
      type: object
      properties:
        '@type':
          const: http://www.w3.org/2001/XMLSchema#dateTime
        '@value':
          type: string
  'http://www.w3.org/ns/prov#endedAtTime':
    description: End time in expanded form
    type: array
  'http://www.w3.org/ns/prov#wasAssociatedWith':
    description: Associated agents in expanded form
    type: array
  'http://purl.org/wf4ever/wfprov#describedByProcess':
    description: Described by process in expanded form
    type: array
  'http://purl.org/wf4ever/wfprov#describedByWorkflow':
    description: Described by workflow in expanded form  
    type: array
  describedByProcess:
    type: string
    format: uri
    description: Links to the process description (compact form)
    x-jsonld-id: http://purl.org/wf4ever/wfprov#describedByProcess
    x-jsonld-type: '@id'
  usedInput:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          format: uri
      required:
        - id
    description: Input artifacts used by this process run
  startedAtTime:
    type: string
    format: date-time
    description: Start time of the execution (compact form)
  endedAtTime:
    type: string
    format: date-time
    description: End time of the execution (compact form)
  wasPartOfWorkflowRun:
    type: string
    format: uri
    description: The workflow run that this process run was part of
    x-jsonld-id: http://purl.org/wf4ever/wfprov#wasPartOfWorkflowRun
    x-jsonld-type: '@id'
  wasEnactedBy:
    type: string
    format: uri
    description: The workflow engine that enacted this process run
    x-jsonld-id: http://www.w3.org/ns/prov#wasAssociatedWith
    x-jsonld-type: '@id'
# Accept either compact id or expanded @id
anyOf:
  - required: [id]
  - required: ['@id']
