{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://purl.org/wf4ever/roterms",
  "title": "WorkflowValue",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Name of the workflow value."
    },
    "value": {
      "description": "The actual value."
    }
  },
  "required": ["value"]
}
