{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://purl.org/wf4ever/roterms",
  "title": "Manuscript",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Title of the manuscript."
    },
    "description": {
      "type": "string",
      "description": "Description of the manuscript."
    }
  },
  "required": ["name"]
}
