$schema: https://json-schema.org/draft/2020-12/schema
description: A data entity used or generated during workflow execution (based on prov:Entity)
type: object
properties:
  id:
    type: string
    format: uri
    description: Unique identifier for the artifact
    x-jsonld-id: '@id'
  type:
    type: string
    description: Type indicator (Entity or sub-type)
    x-jsonld-id: '@type'
  describedByParameter:
    type: string
    format: uri
    description: Links to the parameter description (Input or Output) that this artifact corresponds to
    x-jsonld-id: http://purl.org/wf4ever/wfprov#describedByParameter
    x-jsonld-type: '@id'
  value:
    description: The actual value or reference to the artifact data
  wasOutputFrom:
    type: string
    format: uri
    description: The process run that generated this artifact
    x-jsonld-id: http://purl.org/wf4ever/wfprov#wasOutputFrom
    x-jsonld-type: '@id'
  checksum:
    type: object
    properties:
      algorithm:
        type: string
        enum: ["MD5", "SHA-1", "SHA-256", "SHA-512"]
      value:
        type: string
    description: Checksum information for data integrity
required:
  - id

